//
//  SumInteractor.swift
//  BeiraDoRio
//
//  Created by Tiago Chaves on 03/03/20.
//  Copyright (c) 2020 Tempest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SumBusinessLogic {
//    func doSomething(request: Sum.Something.Request)
}

protocol SumDataStore {
    //var name: String { get set }
}

class SumInteractor: SumBusinessLogic, SumDataStore {
    var presenter: SumPresentationLogic?
//    var worker: SumWorker?
    //var name: String = ""
    
    // MARK: - Do something
//    func doSomething(request: Sum.Something.Request) {
//        worker = SumWorker()
//        worker?.doSomeWork()
//
//        let response = Sum.Something.Response()
//        presenter?.presentSomething(response: response)
//    }
}
