//
//  SumPresenter.swift
//  BeiraDoRio
//
//  Created by Tiago Chaves on 03/03/20.
//  Copyright (c) 2020 Tempest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SumPresentationLogic {
//    func presentSomething(response: Sum.Something.Response)
}

class SumPresenter: SumPresentationLogic {
    weak var viewController: SumDisplayLogic?
    
    // MARK: - Do something
//    func presentSomething(response: Sum.Something.Response) {
//        let viewModel = Sum.Something.ViewModel()
//        viewController?.displaySomething(viewModel: viewModel)
//    }
}
