//
//  SumRouter.swift
//  BeiraDoRio
//
//  Created by Tiago Chaves on 03/03/20.
//  Copyright (c) 2020 Tempest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SumRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?) 
}

protocol SumDataPassing {
    var dataStore: SumDataStore? { get }
}

class SumRouter: NSObject, SumRoutingLogic, SumDataPassing {
    weak var viewController: SumViewController?
    var dataStore: SumDataStore?
    
    // MARK: - Routing
    
//    func routeToSomewhere(segue: UIStoryboardSegue?) {
//        if let segue = segue {
//            let destinationVC = segue.destination as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//        } else {
//            let storyboard = UIStoryboard(name: "Main", bundle: nil)
//            let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//            navigateToSomewhere(source: viewController!, destination: destinationVC)
//        }
//    }
    
    // MARK: - Navigation
    
    //    func navigateToSomewhere(source: SumViewController, destination: SomewhereViewController) {
    //        source.show(destination, sender: nil)
    //    }
    
    // MARK: - Passing data
    //    func passDataToSomewhere(source: SumDataStore, destination: inout SomewhereDataStore) {
    //        destination.name = source.name
    //    }
}
